name: Make Script Executable

on:
  push:
    branches: [ main ]  # Change to your default branch name if it is 'master'

jobs:
  chmod-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x *.py
